language: r
sudo: false
cache: packages

after_success:
  - Rscript -e 'install.packages("covr"); library(covr); codecov(token = "9ee67667-7a10-406c-a982-23c86af5d682" )'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: W/SNFeqFQ9Ezth8VqJtWSL+296iqEvzJQ2SrxrfNx66StjNywRUc8Sp/Yw1/kZHwsHu8pb9uO42yxanSly9LZa235kuG3EkB0hzW6md0kQ9o1fGI/GjOLKW49IE9utJ81e6Pg4e1evNTNQgEk5f4UZHLguNnkOGqUm31VrVal4k=
