language: r
warnings_are_errors: true
sudo: required
env:
  global:
  - CRAN: http://cran.rstudio.com
  - NOT_CRAN: true
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - ./travis-tool.sh bootstrap
install:
  - sudo R CMD javareconf
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests
after_failure:
  - ./travis-tool.sh dump_logs
notifications:
  slack:
    secure: W/SNFeqFQ9Ezth8VqJtWSL+296iqEvzJQ2SrxrfNx66StjNywRUc8Sp/Yw1/kZHwsHu8pb9uO42yxanSly9LZa235kuG3EkB0hzW6md0kQ9o1fGI/GjOLKW49IE9utJ81e6Pg4e1evNTNQgEk5f4UZHLguNnkOGqUm31VrVal4k=
