language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - sudo apt-get install -y libv8-dev
  - ./pkg-build.sh bootstrap

install:
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs


notifications:
  slack:
    secure: W/SNFeqFQ9Ezth8VqJtWSL+296iqEvzJQ2SrxrfNx66StjNywRUc8Sp/Yw1/kZHwsHu8pb9uO42yxanSly9LZa235kuG3EkB0hzW6md0kQ9o1fGI/GjOLKW49IE9utJ81e6Pg4e1evNTNQgEk5f4UZHLguNnkOGqUm31VrVal4k=


env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
